In [1]:
import numpy as np
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d.shape
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [3]:
arr2d[2]

array([7, 8, 9])

In [4]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
#統計使用實體方法
arr = np.random.randint(50,101,size=(10,5))
arr.sum()
arr.sum(0)
arr.sum(axis=1)

array([383, 337, 450, 367, 326, 373, 353, 374, 346, 412])

In [6]:
#使用uumpy內的function
arr = np.random.randint(50,101,size=(10,5))
np.sum(arr)
np.sum(arr,axis=0)
np.sum(arr,axis=1)

array([385, 352, 382, 391, 441, 372, 401, 359, 395, 395])

In [ ]:
#常見的統計方法
#sum
#mean
#std
#max
#min
#median

In [7]:
#cumsum()

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [8]:
oneStore = np.random.randint(100,10000,size=(30,))
oneStore

array([5464, 7638, 9973, 1527, 2917, 7516, 2254,  715, 4735, 8607, 5935,
       1845, 9528, 4063, 4665, 5377, 4353, 6313, 7127, 2492, 2627, 9368,
       3006, 2740, 2639, 1836, 1726, 8805, 3235, 2480])

In [ ]:
import matplotlib.pyplot as plt

fig = plt.figure(figure=(10,5))
axes1 = fig.add_subplot(2,1,1)
axes1.plot(range(1,31),oneStore,'b-')
axes1.set_xticks(range(1,31))

axes2 = fig.add_subplot(2,1,2)
axes2.plot(range(1,31),oneStore.cumsum(),'r')
axes2.set_xticks(range(1, 31))
plt.show()

In [ ]:
five_store = np.random.randint(100,10000,size=(5,30))
five_store_cumsum = five_store.cumsum(axis=1)
five_store_cumsum

In [ ]:
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,5))
axes = fig.add_subplot()
axes.set_xticks(range(1,31))
axes.grid(axis='x')
for one in five_store_cumsum:
    axes.plot(range(1,31),one)

plt.show()